# Используем официальный образ GCC
FROM gcc:latest

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем исходный код
COPY main.cpp .

# Компилируем приложение
RUN g++ -o myapp main.cpp -static

# Запускаем приложение
CMD ["./myapp"]